### ISSUE TITLE
Generate folders under container-volume as group root

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#131]
The generator should change the group of the folders under container-volume to "root" and allow write access to the group.

**Comment by ufasoli** [comment]
Run from the container using the -user flag

**Comment by gschmutz** [comment]
I'm not sure if this is solved with the -user flag. In the printus project we were starting to set the group of all folders to Root, leaving the owner to the user who uses Platys. Think the reason for doing that, was that some containers run under root and then have problems with the volume mappings.

**Comment by ufasoli** [comment]
Add an option to the script allow python to change the permission of the folder of the container-volumes to write permissions to the group
