### ISSUE TITLE
Spark 2.4.5 docker image unknown

### ISSUE THREAD

**Issue by nautilus-dev** [TrivadisPF/platys-modern-data-platform#218]
When starting a generated stack with Spark enabled I receive:
ERROR: manifest for trivadis/apache-spark-master:2.4.5-hadoop2.8 not found: manifest unknown: manifest unknown

In https://hub.docker.com/r/trivadis/apache-spark-master/tags?page=1&ordering=-last_updated
 there is 2.4.6 available.

Changing the minor version from 5 to 6 resolves the issue. 
==> This applies for the spark referenced images (master, worker, history, thrift, ...)

Regards, Philip

**Comment by gschmutz** [comment]
I have recreated the 2.4.5-hadoop2.8 tag of the spark images.
