### ISSUE TITLE
overview-platys-command.md missing 

### ISSUE THREAD

**Issue by mmuehlbeyer** [TrivadisPF/platys-modern-data-platform#233]
overview-platys-command.md  is linked on several pages/sites but not available in the repo

e.g. https://github.com/TrivadisPF/platys-modern-data-platform/blob/master/documentation/getting-started.md 
links to https://github.com/TrivadisPF/platys-modern-data-platform/blob/master/documentation/overview-platys-command.md which leads to an 404 error

**Comment by gschmutz** [comment]
thanks for reporting, fixed in development branch, will release 1.9.0 at the end of the week.
