### ISSUE TITLE
Metabase issue

### ISSUE THREAD

**Issue by johnfelipe** [TrivadisPF/platys-modern-data-platform#520]
http://192.168.0.17:28257/

![SNAG-0062](https://user-images.githubusercontent.com/428820/182048704-2a37171b-b9f5-4d81-a72c-19467c0ad38c.png)

![SNAG-0063](https://user-images.githubusercontent.com/428820/182048721-b1a6e8bd-2d00-44b0-a0ab-9be1bd249adc.png)

wich is next step in here?

**Comment by johnfelipe** [comment]
wich is credentials and path correct in chrome?

**Comment by gschmutz** [comment]
@johnfelipe  I'm not sure what your problem is. When you start Metabase for the first time there is a wizard where you can go through and register yourself (email and password among other information). With that as the last step you will get to the metabase UI.

**Comment by johnfelipe** [comment]
Wich one is url and credentials by default?

**Comment by gschmutz** [comment]
there are none by default, you have to register through the wizzard I believe. Can cross check if the docker image allows to bypass the wizzard ..... but at the moment you need to use the wizzard.

**Comment by johnfelipe** [comment]
But wizard not charge, IP:port only show that, or Wich is url?

**Comment by gschmutz** [comment]
you should get forwarded to

<http://147.87.118.60:28257/setup> 

when navigating to http://147.87.118.60:28257/
