### ISSUE TITLE
Update pls - platys-modern-data-platform/cookbooks/recipes/cassandra/

### ISSUE THREAD

**Issue by johnfelipe** [TrivadisPF/platys-modern-data-platform#542]
Not found

https://github.com/TrivadisPF/platys-modern-data-platform/blob/master/cookbooks/recipes/documentation/getting-started.md

**Comment by gschmutz** [comment]
@johnfelipe do you remember where you have found that link? Guess it is just wrong and should point to <https://github.com/TrivadisPF/platys-modern-data-platform/blob/master/documentation/getting-started.md>

**Comment by johnfelipe** [comment]
Fix that, path is in title

**Comment by gschmutz** [comment]
done
