### ISSUE TITLE
Question: how can edit env.sh for allow connection via telnet to ip:7199

### ISSUE THREAD

**Issue by johnfelipe** [TrivadisPF/platys-modern-data-platform#590]
https://www.liquidweb.com/kb/error-failed-to-connect-to-127-0-0-17199-connection-refused-cassandra-solved/

I need to configure or edit

JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=0.0.0.0"

Pls help me asap

**Comment by gschmutz** [comment]
close it because I don't think it is relevant any longer. There was another issue around the `nodetool`.
