### ISSUE TITLE
how can deploy jupyter for call all spark cluster?

### ISSUE THREAD

**Issue by johnfelipe** [TrivadisPF/platys-modern-data-platform#594]
wich will be best option and settings for deploy jupyter for work with spark cluster, not like spark library?

**Comment by johnfelipe** [comment]
jupyter who is in the spark, mount it not as a bookshop but as a spark cluster
pls tell me how can configure spark cluster not like a library

**Comment by gschmutz** [comment]
Check the following cookbook recipe: <https://github.com/TrivadisPF/platys-modern-data-platform/blob/develop/cookbooks/recipes/jupyter-spark/README.md>
