### ISSUE TITLE
ADD: cassandra web with login credentials in webUI

### ISSUE THREAD

**Issue by johnfelipe** [TrivadisPF/platys-modern-data-platform#596]
http://192.168.144.52:28120/

![SNAG-0256](https://user-images.githubusercontent.com/428820/197613558-7854b922-dd8f-4cf8-96b9-0a34fa8137f4.png)

or

![SNAG-0257](https://user-images.githubusercontent.com/428820/197614002-277b9632-5be2-4367-aefe-28353732a90f.png)

or

![SNAG-0258](https://user-images.githubusercontent.com/428820/197614317-63774ee9-569a-4afe-b180-07edcea6f880.png)

For example there have before a login credentials, is something already setted in your stack, or pls add something for put credentials in each UI, that will be great and helpfully

**Comment by gschmutz** [comment]
I can't add login if the tool does not support it, for example cassandra-web does not support authentication. For the web viewer (port 80) with the list of services I don't think that authentication is needed as this is just the "view" into the platform.

Will make the cassandra-web configurable, so it can be disabled.

**Comment by johnfelipe** [comment]
that is a good idea, cassandra web configurable, if allow or not

**Comment by gschmutz** [comment]
cassandra-web is now configurable via setting `CASSANDRA_WEB_enable`
