### ISSUE TITLE
Pls explain how to use Jupyter hub with credentials

### ISSUE THREAD

**Issue by johnfelipe** [TrivadisPF/platys-modern-data-platform#597]

**Comment by gschmutz** [comment]
WIth the new version `1.16.0` a default `userlist` file is mapped into JupyterHub with an admin user named `jupyterhub`. For the password the setting of `JUPYTERHUB_global_password` is used (`abc123!` by default).
A custom `userlist` file can be configured in `custom-conf/jupyterhub` by setting `JUPYTERHUB_use_custom_userlist` to `true`.
