### ISSUE TITLE
datahub credentials?

### ISSUE THREAD

**Issue by johnfelipe** [TrivadisPF/platys-modern-data-platform#598]
im trying to use
admin:admin
datahub:datahub
admin:abc123!abc123!
datahub:abc123!abc123!

and anyone works
Pls tell me wich is exactly credentials?
Pls view this video: https://drive.google.com/file/d/1ZxC8p7cgdp07pCnuDF2W2JuA3WBHNC40/view?usp=drivesdk
stay alert

**Comment by johnfelipe** [comment]
dear r u there, pls tell me slots of time in your hourly or in COT for begin solve all my issues
stay alert

**Comment by johnfelipe** [comment]
??

**Comment by gschmutz** [comment]
user  is `datahub` and password is `datahub`
