### ISSUE TITLE
Support for creating a Cassandra cluster

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys-modern-data-platform#60]
Current cassandra only supports a single node installation. Add support for multiple cassandra nodes.

**Comment by johnfelipe** [comment]
This is already done?
How can add nodes into?

**Comment by gschmutz** [comment]
@johnfelipe  It is supported for DataStax but not yet for Cassandra. Will try to add support for it this weekend. Keep you updated....

**Comment by johnfelipe** [comment]
ping me when is done pls

**Comment by gschmutz** [comment]
@johnfelipe cassandra cluster is now supported and currently available in the 1.15.0-preview. Will release 1.15.0 soon.
