### ISSUE TITLE
how can solve issue when server physically restart cassandra restore credentials to cassandra/cassandra

### ISSUE THREAD

**Issue by johnfelipe** [TrivadisPF/platys-modern-data-platform#607]
How can solve that issue, pls

**Comment by gschmutz** [comment]
Did you configure anything manually inside the running container? 
You should never do that as it is not persisted and you will loose it when recreating the containers.

**Comment by johnfelipe** [comment]
No, server physically down, and my new cassandra credentials restore to cassandra/cassandra....

```
docker exec -ti cassandra-1 bash

cqlsh -u cassandra -p cassandra

cqlsh localhost -u cassandra -p blablablablabla
```

how can change then that credentials?
